# Configuration for PUBLIC distribution app with Billing API
# Public app: escriv-ecom

client_id = "218950dbb1b01721766854e2d4382769"
name = "escriv-ecom"
handle = "escriv-ecom-1"
<<<<<<< HEAD
application_url = "https://renewable-ambient-rw-creator.trycloudflare.com"
=======
application_url = "https://dame-perry-hair-je.trycloudflare.com"
>>>>>>> exp
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_locations, read_orders, read_products, write_inventory, write_products"

[auth]
<<<<<<< HEAD
redirect_urls = ["https://renewable-ambient-rw-creator.trycloudflare.com/auth/callback", "https://renewable-ambient-rw-creator.trycloudflare.com/auth/shopify/callback", "https://renewable-ambient-rw-creator.trycloudflare.com/api/auth/callback"]
=======
redirect_urls = ["https://dame-perry-hair-je.trycloudflare.com/auth/callback", "https://dame-perry-hair-je.trycloudflare.com/auth/shopify/callback", "https://dame-perry-hair-je.trycloudflare.com/api/auth/callback"]
>>>>>>> exp

[pos]
embedded = false
